### ISSUE TITLE
파싱에러 관련

### ISSUE THREAD

**Issue by hohomang** [ssut/py-hanspell#17]
아래와 같이 에러가 발생했는데요, 혹시 사유를 알 수 있을까요?

Traceback (most recent call last):
  File "C:/homin/prod_spellcheck.py", line 50, in <module>
    spell_check()
  File "C:/homin/prod_spellcheck.py", line 33, in spell_check
    result = spell_checker.check(unchktext)
  File "C:\Users\KTds_User\AppData\Local\Programs\Python\Python38\lib\site-packages\py_hanspell-1.1-py3.8.egg\hanspell\spell_checker.py", line 39, in check
  File "C:\Users\KTds_User\AppData\Local\Programs\Python\Python38\lib\site-packages\py_hanspell-1.1-py3.8.egg\hanspell\spell_checker.py", line 68, in check
  File "C:\Users\KTds_User\AppData\Local\Programs\Python\Python38\lib\site-packages\py_hanspell-1.1-py3.8.egg\hanspell\spell_checker.py", line 27, in _remove_tags
  File "C:\Users\KTds_User\AppData\Local\Programs\Python\Python38\lib\xml\etree\ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1200

**Comment by hohomang** [comment]
특수문자 때문이었네요 해결했습니다.
