### ISSUE TITLE
ParseError

### ISSUE THREAD

**Issue by bbq12340** [ssut/py-hanspell#19]
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    df = process_data(df)
  File "main.py", line 19, in process_data
    processed_reviews = process_reviews(cleaned_reviews)
  File "/Users/bbq12340/dev/sentimentAnalysis/process.py", line 25, in process_reviews
    review = spell_checker.check(review).as_dict()['checked']
  File "/Users/bbq12340/dev/sentimentAnalysis/env/lib/python3.8/site-packages/hanspell/spell_checker.py", line 68, in check
    'checked': _remove_tags(html),
  File "/Users/bbq12340/dev/sentimentAnalysis/env/lib/python3.8/site-packages/hanspell/spell_checker.py", line 27, in _remove_tags
    result = ''.join(ET.fromstring(text).itertext())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 226

파싱하는 과정에서 에러가 발생하였습니다. 에러 발생을 방지해야 할 것 같습니다.

**Comment by oneonlee** [comment]
저도 같은 에러가 발생하네요

**Comment by JINHEE-KANG** [comment]
저도 같은 에러가 발생합니다

**Comment by lhy0718** [comment]
`spell_checker.py`의 `_remove_tags` 함수 안을 다음과 같이 바꾸었더니 문제가 해결되었습니다.

`result = "".join(ET.fromstring(text).itertext())` 이 부분을

```
from lxml import etree # pip install lxml 필요

....

parser = etree.XMLParser(recover=True)
result = "".join(etree.fromstring(text, parser=parser).itertext())
```
와 같이 바꾸어주세요.

레퍼런스: https://stackoverflow.com/questions/13046240/parseerror-not-well-formed-invalid-token-using-celementtree
