### ISSUE TITLE
[BUG] pip install

### ISSUE THREAD

**Issue by TaeGuNi** [ssut/py-hanspell#3]
'requirements.txt' 파일이 누락되었습니다.

```
$ pip install py-hanspell
Collecting py-hanspell
  Downloading py-hanspell-1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dc416kan/py-hanspell/setup.py", line 40, in <module>
        install()
      File "/tmp/pip-build-dc416kan/py-hanspell/setup.py", line 7, in install
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dc416kan/py-hanspell/
```

**Comment by fly0159** [comment]
git clone으로 받아서 하시면 됩니다!
