### ISSUE TITLE
[이슈 문의] KeyError: 'result'

### ISSUE THREAD

**Issue by SungbinYang** [ssut/py-hanspell#50]
안녕하세요. 현재 파이썬 버전 3.10.10을 사용하고 있으며 README.md에서 제공한 예제를 돌려본 결과 아래의 에러가 발생합니다.

```
Traceback (most recent call last):
  File "c:\~\spell.py", line 3, in <module>
    result = spell_checker.check(u'안녕 하세요. 저는 한국인 입니다. 이문장은 한글로 작성됬습니다.')
  File "c:\~\lib\hanspell\spell_checker.py", line 62, in check
    html = data['message']['result']['html']
KeyError: 'result'
```

해당 문제에 대해 제가 놓치고 있는 부분이 있는지 알고 싶습니다.

**Comment by mysunk** [comment]
인증문제인데 #47 #48 등등 확인해보세요!

**Comment by SungbinYang** [comment]
> 인증문제인데 #47 #48 등등 확인해보세요!

감사합니다! 한번 확인해보겠습니다!
