### ISSUE TITLE
패키지 설치 오류

### ISSUE THREAD

**Issue by LeeSY99** [ssut/py-hanspell#51]
Collecting py-hanspell
  Using cached py-hanspell-1.1.tar.gz (3.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-np815kcr/py-hanspell_6bee0fb3c65e460b97f9b638d6b57545/setup.py", line 2, in <module>
          from pip.req import parse_requirements
      ModuleNotFoundError: No module named 'pip.req'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

라는 오류는 왜 뜨는 걸까요?

**Comment by vividbaek** [comment]
저도 동일한 오류가 발생하여서 다른 방법으로 진행했습니다.
1. git clone 진행
2.  $ python setup.py install 설치
3.  git clone 진행한 폴더 안에서 실행(단, passport key 이슈가 발생하여서 추가하셔야 합니다.)

**Comment by lhy0718** [comment]
`pip instll git+https://github.com/ssut/py-hanspell` 으로도 가능합니다.
