### ISSUE TITLE
pip.req 에러

### ISSUE THREAD

**Issue by hyun06000** [ssut/py-hanspell#6]
설치시에 pip.req라는 모듈이 없어서 오류가 난다고 합니다.

스텍오버플로에서 임시적인 해결법을 찾았지만 혹시 조금 더 근원적인 해결이 가능한지 알고싶습니다.

멋진 코드에 감사드립니다.

**Comment by ssut** [comment]
헉 아직 이 라이브러리가 잘 작동하는지부터 확인해봐야 할 것 같습니다. 확인 후 코드 다시 올려볼게요.

**Comment by harplife** [comment]
오늘 처음 사용해보려고 하는데.. 여전히 `MoudleNotFoundError: No module named 'pip.req'` 에러가 나오네요~

**Comment by snoop2head** [comment]
저도 비슷한 에러가 생겼습니다ㅠㅠ

Collecting py-hanspell
  Using cached py-hanspell-1.1.tar.gz (3.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/noopy/.local/share/virtualenvs/django-airbnb-clone-AcLC9Tzu/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-install-4wlej1v0/py-hanspell/setup.py'"'"'; __file__='"'"'/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-install-4wlej1v0/py-hanspell/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-install-4wlej1v0/py-hanspell/pip-egg-info
         cwd: /private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-install-4wlej1v0/py-hanspell/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-install-4wlej1v0/py-hanspell/setup.py", line 2, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by yangkyeongmo** [comment]
setup.py 파일에 **from pip.req import parse_requirements를 지우고 재실행**했더니 해결되었습니다.

**Comment by snoop2head** [comment]
@yangkyeongmo  아하... PR에 반영된 내용들을 살펴봤어야 했는데 ㅎㅎㅎ 감사합니다!
